globalThis.siteContent = {
packages:[
{id:'bronze',name:'Bronce',price:10000,includes:['Capilla de velación y/o velación en domicilio','Traslados locales en carroza','Trámites de gobierno','Cremación y/o sepultura','Aseo y vestimenta'],excludes:['Certificado de defunción','Lugar en panteón','Embalsamado']},
{id:'silver',name:'Plata',price:15000,includes:['Capilla de velación','Ataúd de madera para velar o sepultar','Trámites de gobierno','Embalsamado','Aseo y arreglo estético','Servicio de carrozas locales'],excludes:['Florería','Cafetería','Servicio religioso']},
{id:'gold',name:'Oro',price:20000,includes:['Capilla de velación con capacidad para más de 50 personas','Trámites de gobierno','Embalsamado','Aseo y arreglo estético','Ataúd de madera de pino para velar y/o sepultar','Traslados en carroza','Arreglo floral','Cafetería de cortesía'],excludes:['Certificado de defunción']}
],
services:[['Cremación','Una alternativa de despedida con un acompañamiento respetuoso.'],['Servicio funerario','Orientación y atención para una despedida digna.'],['Sepultura','Acompañamiento para despedir a tu ser querido.'],['Exhumación','Consulta las opciones y requisitos para este servicio.'],['Traslados','Te orientamos sobre las opciones para tu ubicación.']],
faq:[['¿Atienden las 24 horas?','Sí. Puedes contactarnos las 24 horas, los 7 días de la semana, por teléfono o WhatsApp.'],['¿Qué zonas cubren?','Ciudad de México y Estado de México, incluyendo Coacalco, Ecatepec, Tultitlán y Tultepec. Comparte tu ubicación para consultar las opciones disponibles.'],['¿Qué incluye un servicio funerario?','Depende del paquete que elijas. En esta página puedes consultar los precios, inclusiones y exclusiones de Bronce, Plata y Oro. Te orientamos antes de contratar.'],['¿Qué documentos se necesitan?','Contáctanos e indícanos la ubicación de la persona fallecida y el servicio que necesitas. Un asesor te orientará sobre los documentos y trámites aplicables a tu caso.'],['¿Cómo elijo entre cremación y sepultura?','Ofrecemos ambas opciones. Podemos orientarte sobre su alcance y los paquetes disponibles para que elijas de acuerdo con las preferencias de tu familia.'],['¿Puedo contratar por teléfono o WhatsApp?','Sí. La contratación puede cerrarse por teléfono o WhatsApp; no es obligatorio acudir físicamente. Se requiere anticipo.'],['¿Aceptan tarjeta y pagos a plazos?','Se acepta efectivo, transferencia y tarjeta mediante TPV. Existe la posibilidad de pagos a plazos o financiamiento; consulta condiciones con un asesor.'],['¿Los paquetes incluyen certificado de defunción?','Bronce y Oro no incluyen certificado de defunción. Para Plata, consulta este punto con un asesor antes de contratar.'],['¿Puedo agregar servicios adicionales?','Sí. Puedes consultar certificado médico, florería, cafetería, servicio religioso, autobús de acompañamiento y noche extra de velación. La disponibilidad y el precio se confirman por contacto directo.']],
testimonials:[]
};
